name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          npm install -- forces
          npm run build -- --configuration production

      - name: Deploy to Nginx
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/sectoriel-web/*"
          target: "/var/www/html/sectoriel-web"
