name: Deploy Angular App

on:
  push:
    branches:
      - main   # déclenche uniquement sur la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./sectoriel-web   # 🔹 change si ton Angular est dans un sous-dossier

      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: ./sectoriel-web   # 🔹 adapte le chemin

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "sectoriel-web/dist/sectoriel-web/*"   # 🔹 vérifie bien que c’est le bon dossier de sortie
          target: "/var/www/html/sectoriel-web"
